### PR TITLE
toolchain JDK to 1.8 and latest ehcache

### PR DESCRIPTION
**Pull request by akomakom**

### CODE REVIEW

**Review by chrisdennis — COMMENTED** [review]
I guess this might be correct in principle but I question the motivation for the existence of this change.

**Comment by akomakom** [comment]
:zombie: 

Did you mean "chain" as in `toolchain` or "chain" as in `project`?

**Comment by chrisdennis** [comment]
I meant `chain` as in `change`.

**Comment by akomakom** [comment]
PRs would fail, if there were any.

**Review by chrisdennis — APPROVED** [review]

**Pull request merged**
